[Feat] 수정 및 삭제 기능 구현
DeveloperAcademy-POSTECH/MC2-Team7-Larasy pull request #37
Opened 2022-09-17 11:14 UTC by JIWON1923

## Keychanges
- Coredata
- 수정 기능
- 삭제 기능

## Screenshots
### 1. iPhone13, iOS 15.5 편집 기능
- 파일 크기가 커서 동영상 두개로 나누어 올려놓았습니다.
- 수정 후 리스트 뷰를 업데이트 할 수 있어야합니다!

https://user-images.githubusercontent.com/68676844/190853692-613ccfa2-0b20-4d80-af3c-7617b6d5934e.mp4

https://user-images.githubusercontent.com/68676844/190853704-c6922275-4fb5-4015-91c8-0c97ed62db8d.mp4

### 2. iPhone13, iOS 15.5 삭제 기능
- 노래가 두 개 이상 있을 때, 이슈가 존재합니다.
- 삭제 후 리스트 뷰 업데이트가 되면, 같이 해결되는 문제입니다.

https://user-images.githubusercontent.com/68676844/190853566-d6746339-9308-439d-b06a-0d2e2f38384b.mp4

### 3. iPhone13, iOS 16.0 (이슈 존재)
- 툴바의 위치를 보시면 됩니다. iOS에 툴바 관련 이슈가 존재하는지 확인 및 대응이 필요합니다.
<img src = "https://user-images.githubusercontent.com/68676844/190853340-fd603b2e-c543-4cc5-9ce3-961613b83908.png" width = 250>

## To Reviewer
- 현재 수정 후 뷰의 업데이트가 되지 않습니다.
- 16일 회의 내용에 따라 머지 후 두 번째 스프린트 진행하고자 합니다.
- 추후 진행되어야하는 상황은 이슈에 올려놓겠습니다!
- Xcode 업데이트 후 메인 화면

2022-09-17 13:05 UTC, YunSeok-Choi reviewed
왕따봉! 👍

2022-09-18 07:45 UTC, JIWON1923 commented on Record/CdListView.swift
> +            }
cd List View에서 DetailView로 이동할 수 있습니다. 
디테일 뷰에서 삭제 이벤트가 발생하고, 다시 리스트뷰로 돌아왔을 때, 없는 값을 참조하는 경우가 발생했습니다. (앱 종료로 이어짐)
그래서 뷰가 나타날 때도 한 번 더 초기화를 진행해주었습니다!! 🔥

2022-09-18 07:52 UTC, YunSeok-Choi commented on Record/CdListView.swift
> +            }
최고최고!👍👍

2022-09-18 07:54 UTC, YunSeok-Choi requested changes
conflict 해결되면 머지해도 좋을 것 같습니다!

2022-09-18 14:15 UTC, YunSeok-Choi approved these changes
LGTM~

2022-09-18 14:24 UTC, merged